### ISSUE TITLE
Naming of `binary_encoder` and `binary_decoder`

### ISSUE THREAD

**Issue by dalance** [veryl-lang/std#15]
The naming `binary_encoder` and `binary_decoder` may be bit confusable.
According to the description, `unary_encoder` and `unary_decoder` may be more suitable?

**Comment by dalance** [comment]
I'll change this module to private temporary. #14 
After fixed the naming, I'll change to public.

**Comment by nblei** [comment]
The English term for hardware which converts between binary and unary representations is, in fact, binary encoder (unary -> binary) and binary decoder (binary -> unary).  See [Binary Encoder](https://en.wikipedia.org/wiki/Encoder_\(Digital\)) and [Binary Decoder](https://en.wikipedia.org/wiki/Binary_decoder).

By duality, I think we would have binary_encoder = unary_decoder and binary_decoder = unary_encoder if you would like aliases for these modules.

**Comment by dalance** [comment]
Thanks!
I didn't know the term, but it seems to be appropriate.
I'll revert to public as it is.
